lst1=([1,2,3],[4,5,6])
import numpy as np
nplst = np.array(lst1)
print("numpy 2d array:(matrix):\n",nplst)
totalSum = np.sum(nplst)
print("Total sum of matrix:",totalSum)
rowSums = np.sum(nplst, axis=1)
print("Sum of elements in rows:",rowSums)
colSums = np.sum(nplst, axis=0)
print("Sum of elements in columns:",colSums)
print("Transpose of matrix:\n",nplst.T)
print("Maximum value in matrix:",np.max(nplst))
print("Minimum value in matrix:",np.min(nplst))
print("Flattened array of above matrix:",nplst.flatten())
print("mean of matrix elements:",np.mean(nplst))
print("standard deviation of matrix elements:",np.std(nplst))